name: Every 30 mins Job

on:
  schedule:
    - cron: '0/30 * * * *'  # every 30mins
  workflow_dispatch:      # allows manual triggering

concurrency:
  group: ${{ github.workflow }}  # 👈 Ensures uniqueness automatically
  cancel-in-progress: true

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # adjust to your script's requirement

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt

      - name: Run script
        env:
          FIFTEEN_MINS_WEBHOOK: ${{ secrets.FIFTEEN_MINS_WEBHOOK }}
          ONE_HOUR_WEBHOOK: ${{ secrets.ONE_HOUR_WEBHOOK }}
        run: python 15min_1hour.py
